/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        String boldAnsi = "\033[1m";
        String redAnsi = "\033[31m";
        String resetAnsi = "\033[0m";

        String appTitle = "[팀 프로젝트 관리 시스템]";
        String line = "-----------------------------------------------";
        String menu1 = "1. 회원";
        String menu2 = "2. 팀";
        String menu3 = "3. 프로젝트";
        String menu4 = "4. 게시판";
        String menu5 = "5. 도움말";
        String menu6 = "6. 종료";

        Scanner sc = new Scanner(System.in);

        int menuNo = 0;
        boolean exitFlag = true;

        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + appTitle +resetAnsi);
        System.out.println(menu1);
        System.out.println(menu2);
        System.out.println(menu3);
        System.out.println(menu4);
        System.out.println(menu5);
        System.out.println(boldAnsi + redAnsi + menu6 + resetAnsi);
        System.out.println(boldAnsi + line + resetAnsi);

        while (exitFlag) {
            System.out.print("< ");
            menuNo = sc.nextInt();
            if (menuNo == 1) {
                System.out.println("회원");
            } else if (menuNo == 2) {
                System.out.println("팀");
            } else if (menuNo == 3) {
                System.out.println("프로젝트");
            } else if (menuNo == 4) {
                System.out.println("게시판");
            } else if (menuNo == 5) {
                System.out.println("도움말");
            } else if(menuNo == 6) {
                System.out.println("종료합니다.");
                exitFlag = false;
            } else {
                System.out.println("메뉴 번호가 옳지 않습니다.");
            }
        }
        // 사용을 완료한 자원은 반환해야 다른 프로세스(프로그램)이 사용할 수 있다.
        // 단, JVM을 종료하면 JVM이 사용한 모든 자원은 강제 회수된다.
        // OS가 강제 회수한다.
        sc.close();
    }
}
